[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Documents"
desc = "Cd to ~/Documents"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /mnt/media/gemensam/AI/ComfyUI"
desc = "Gå till gemensamma ComfyUI-mappen"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "cd /home/thhel/comfy"
desc = "Gå till Comfy-mappen"

[[mgr.prepend_keymap]]
on = ["p", "p"]
run = 'shell --orphan "mpv --video-unscaled ."'
desc = "Play current directory in MPV"

[[mgr.prepend_keymap]]
on = ["p", "v"]
run = 'shell --orphan "find . -maxdepth 1 -type f -exec file --mime-type {} + | grep \"video/\" | cut -d: -f1 | xargs -d \"\\n\" mpv --video-unscaled"'
desc = "Spela alla videofiler i mappen"

[[mgr.prepend_keymap]]
on = ["p", "V"]
run = 'shell --orphan "find . -maxdepth 5 -type f -exec file --mime-type {} + | grep \"video/\" | cut -d: -f1 | xargs -d \"\\n\" mpv --video-unscaled"'
desc = "Spela alla videofiler i mappen rekursivt"

[[mgr.prepend_keymap]]
on = ["p", "i"]
run = 'shell --orphan "find . -maxdepth 1 -type f -exec file --mime-type {} + | grep \"image/\" | cut -d: -f1 | xargs -d \"\\n\" mpv --video-unscaled"'
desc = "Spela alla videofiler i mappen"

[[mgr.prepend_keymap]]
on = ["p", "I"]
run = 'shell --orphan "find . -maxdepth 5 -type f -exec file --mime-type {} + | grep \"image/\" | cut -d: -f1 | xargs -d \"\\n\" mpv --video-unscaled"'
desc = "Spela alla videofiler i mappen rekursivt"
